version: 1.0.{build}

environment:
  NAME: file.bin
  URL: https://github.com/containous/traefik/releases/download/v2.0.0/traefik_v2.0.0_windows_amd64.zip

build_script:
- cmd: echo %URL%
- cmd: curl -fsSL -o %NAME% %URL%

artifacts:
- path: $(NAME)
