version: 1.0.{build}

environment:
  NAME: file.bin
  URL: https://github.com/PowerShell/PowerShell/releases/download/v6.2.2/PowerShell-6.2.2-win-x64.zip

build_script:
- cmd: echo %URL%
- cmd: curl -fsSL -o %NAME% %URL%

artifacts:
- path: $(NAME)
