version: 1.0.{build}

environment:
  NAME: file.bin
  URL: https://files.dev47apps.net/DroidCam.Setup.6.3.1.exe

build_script:
- cmd: echo %URL%
- cmd: curl -fsSL -o %NAME% %URL%

artifacts:
- path: $(NAME)
