version: 1.0.{build}

environment:
  NAME: file.bin
  URL: https://github.com/PowerShell/PowerShellEditorServices/releases/download/v1.12.2/PowerShellEditorServices.zip

build_script:
- cmd: echo %URL%
- cmd: curl -fsSL -o %NAME% %URL%

artifacts:
- path: $(NAME)
